using System;
using System.Collections.Generic;

namespace ActiveProbe.Domain.Models
{
    public partial class InfoPacket
    {
        public long Id { get; set; }
        public int MachineId { get; set; }
        public byte ChannelId { get; set; }
        public DateTime RecvDt { get; set; }
        public DateTime Gpsdt { get; set; }
        public float? Lat { get; set; }
        public float? Lon { get; set; }
        public short? Alt { get; set; }
        public float? Speed { get; set; }
        public short? Direction { get; set; }
        public bool Gpsvalidity { get; set; }
        public byte? NoOfSats { get; set; }
        public byte? Gpsdop { get; set; }
        public byte DeviceStatus { get; set; }
        public float BatteryVoltage { get; set; }
        public float InputVoltage { get; set; }
        public byte EventCode { get; set; }
        public byte? Op { get; set; }
        public byte? ForceG2IdleSystem { get; set; }
        public short? ForceG2IdleMcc { get; set; }
        public byte? ForceG2IdleMnc { get; set; }
        public byte? ForceG2IdleBsic { get; set; }
        public int? ForceG2IdleLac { get; set; }
        public short? ForceG2IdleArfcn { get; set; }
        public int? ForceG2IdleCellId { get; set; }
        public short? ForceG2IdleRxLev { get; set; }
        public byte? ForceG2VoiceSystem { get; set; }
        public short? ForceG2VoiceMcc { get; set; }
        public byte? ForceG2VoiceMnc { get; set; }
        public byte? ForceG2VoiceBsic { get; set; }
        public int? ForceG2VoiceLac { get; set; }
        public short? ForceG2VoiceArfcn { get; set; }
        public int? ForceG2VoiceCellId { get; set; }
        public short? ForceG2VoiceRxLev { get; set; }
        public byte? ForceG2VoiceTa { get; set; }
        public byte? ForceG2VoiceTxPwr { get; set; }
        public byte? ForceG2VoiceRxQual { get; set; }
        public byte[] ForceG2Call { get; set; }
        public byte? ForceG2PingPSent { get; set; }
        public byte? ForceG2PingPRec { get; set; }
        public byte? ForceG2PingPLost { get; set; }
        public short? ForceG2PingRttMin { get; set; }
        public short? ForceG2PingRttMax { get; set; }
        public short? ForceG2PingRttAvg { get; set; }
        public byte? ForceG3IdleSystem { get; set; }
        public short? ForceG3IdleMcc { get; set; }
        public byte? ForceG3IdleMnc { get; set; }
        public int? ForceG3IdleLac { get; set; }
        public string ForceG3IdleRfBand { get; set; }
        public short? ForceG3IdleRssi { get; set; }
        public short? ForceG3IdlePsc { get; set; }
        public short? ForceG3IdleUarfcn { get; set; }
        public short? ForceG3IdleRxLev { get; set; }
        public float? ForceG3IdleEcio { get; set; }
        public int? ForceG3IdleId { get; set; }
        public short? ForceG3IdleRscp { get; set; }
        public byte? ForceG3VoiceSystem { get; set; }
        public short? ForceG3VoiceMcc { get; set; }
        public byte? ForceG3VoiceMnc { get; set; }
        public int? ForceG3VoiceLac { get; set; }
        public string ForceG3VoiceRfBand { get; set; }
        public short? ForceG3VoiceRssi { get; set; }
        public short? ForceG3VoicePsc { get; set; }
        public short? ForceG3VoiceUarfcn { get; set; }
        public float? ForceG3VoiceEcio { get; set; }
        public int? ForceG3VoiceId { get; set; }
        public short? ForceG3VoiceRscp { get; set; }
        public short? ForceG3VoiceRxLev { get; set; }
        public byte? ForceG3VoiceTxPwr { get; set; }
        public byte? ForceG3VoiceBer { get; set; }
        public byte[] ForceG3Call { get; set; }
        public byte? ForceG3PingPSent { get; set; }
        public byte? ForceG3PingPRec { get; set; }
        public byte? ForceG3PingPLost { get; set; }
        public short? ForceG3PingRttMin { get; set; }
        public short? ForceG3PingRttMax { get; set; }
        public short? ForceG3PingRttAvg { get; set; }
        public byte? ForceG4System { get; set; }
        public short? ForceG4Mcc { get; set; }
        public byte? ForceG4Mnc { get; set; }
        public int? ForceG4Lac { get; set; }
        public short? ForceG4CellId { get; set; }
        public string ForceG4FrqBand { get; set; }
        public short? ForceG4Earfcn { get; set; }
        public byte? ForceG4Dlbw { get; set; }
        public byte? ForceG4Ulbw { get; set; }
        public float? ForceG4Rsrq { get; set; }
        public float? ForceG4Rsrp { get; set; }
        public float? ForceG4Rssi { get; set; }
        public short? ForceG4Rssnr { get; set; }
        public short? ForceG4Sinr { get; set; }
        public byte? ForceG4PingPSent { get; set; }
        public byte? ForceG4PingPRec { get; set; }
        public byte? ForceG4PingPLost { get; set; }
        public short? ForceG4PingRttMin { get; set; }
        public short? ForceG4PingRttMax { get; set; }
        public short? ForceG4PingRttAvg { get; set; }
        public byte? AutoG2IdleSystem { get; set; }
        public short? AutoG2IdleMcc { get; set; }
        public byte? AutoG2IdleMnc { get; set; }
        public byte? AutoG2IdleBsic { get; set; }
        public int? AutoG2IdleLac { get; set; }
        public short? AutoG2IdleArfcn { get; set; }
        public int? AutoG2IdleCellId { get; set; }
        public short? AutoG2IdleRxLev { get; set; }
        public byte? AutoG2VoiceSystem { get; set; }
        public short? AutoG2VoiceMcc { get; set; }
        public byte? AutoG2VoiceMnc { get; set; }
        public byte? AutoG2VoiceBsic { get; set; }
        public int? AutoG2VoiceLac { get; set; }
        public short? AutoG2VoiceArfcn { get; set; }
        public int? AutoG2VoiceCellId { get; set; }
        public short? AutoG2VoiceRxLev { get; set; }
        public byte? AutoG2VoiceTa { get; set; }
        public byte? AutoG2VoiceTxPwr { get; set; }
        public byte? AutoG2VoiceRxQual { get; set; }
        public byte[] AutoG2Call { get; set; }
        public byte? AutoG2PingPSent { get; set; }
        public byte? AutoG2PingPRec { get; set; }
        public byte? AutoG2PingPLost { get; set; }
        public short? AutoG2PingRttMin { get; set; }
        public short? AutoG2PingRttMax { get; set; }
        public short? AutoG2PingRttAvg { get; set; }
        public byte? AutoG3IdleSystem { get; set; }
        public short? AutoG3IdleMcc { get; set; }
        public byte? AutoG3IdleMnc { get; set; }
        public int? AutoG3IdleLac { get; set; }
        public string AutoG3IdleRfBand { get; set; }
        public short? AutoG3IdleRssi { get; set; }
        public short? AutoG3IdlePsc { get; set; }
        public short? AutoG3IdleUarfcn { get; set; }
        public short? AutoG3IdleRxLev { get; set; }
        public float? AutoG3IdleEcio { get; set; }
        public int? AutoG3IdleId { get; set; }
        public short? AutoG3IdleRscp { get; set; }
        public byte? AutoG3VoiceSystem { get; set; }
        public short? AutoG3VoiceMcc { get; set; }
        public byte? AutoG3VoiceMnc { get; set; }
        public int? AutoG3VoiceLac { get; set; }
        public string AutoG3VoiceRfBand { get; set; }
        public short? AutoG3VoiceRssi { get; set; }
        public short? AutoG3VoicePsc { get; set; }
        public short? AutoG3VoiceUarfcn { get; set; }
        public float? AutoG3VoiceEcio { get; set; }
        public int? AutoG3VoiceId { get; set; }
        public short? AutoG3VoiceRscp { get; set; }
        public short? AutoG3VoiceRxLev { get; set; }
        public byte? AutoG3VoiceTxPwr { get; set; }
        public byte? AutoG3VoiceBer { get; set; }
        public byte[] AutoG3Call { get; set; }
        public byte? AutoG3PingPSent { get; set; }
        public byte? AutoG3PingPRec { get; set; }
        public byte? AutoG3PingPLost { get; set; }
        public short? AutoG3PingRttMin { get; set; }
        public short? AutoG3PingRttMax { get; set; }
        public short? AutoG3PingRttAvg { get; set; }
        public byte? AutoG4System { get; set; }
        public short? AutoG4Mcc { get; set; }
        public byte? AutoG4Mnc { get; set; }
        public int? AutoG4Lac { get; set; }
        public short? AutoG4CellId { get; set; }
        public string AutoG4FrqBand { get; set; }
        public short? AutoG4Earfcn { get; set; }
        public byte? AutoG4Dlbw { get; set; }
        public byte? AutoG4Ulbw { get; set; }
        public float? AutoG4Rsrq { get; set; }
        public float? AutoG4Rsrp { get; set; }
        public float? AutoG4Rssi { get; set; }
        public short? AutoG4Rssnr { get; set; }
        public short? AutoG4Sinr { get; set; }
        public byte? AutoG4PingPSent { get; set; }
        public byte? AutoG4PingPRec { get; set; }
        public byte? AutoG4PingPLost { get; set; }
        public short? AutoG4PingRttMin { get; set; }
        public short? AutoG4PingRttMax { get; set; }
        public short? AutoG4PingRttAvg { get; set; }
        public byte? PingIpType { get; set; }
        public byte[] PingIp { get; set; }
        public string PingDomain { get; set; }
    }
}
